"""Terraform export (backlog #12, CONTRACTS §11): agdemo_core.terraform.render and the API endpoint."""
import re
from datetime import datetime, timezone

import pytest

from agdemo_core import terraform as T
from agdemo_core.config import DemoConfig
from agdemo_core.policies.egress_allow import condition
from agdemo_core.themes import load_theme
from test_api import client  # noqa: F401  (shared TestClient fixture)

NOW = datetime(2026, 10, 8, 12, 0, tzinfo=timezone.utc)
PRINCIPAL = ("principal://agents.global.org-1.system.id.goog/resources/aiplatform/projects/42/locations/"
             "us-east4/reasoningEngines/77")
STATE = {
    "shared": {"gateway_service_agents": ["service-99@gcp-sa-dep.iam.gserviceaccount.com"]},
    "themes": {"helpdesk": {
        "orchestrator": {"engine": "projects/42/locations/us-east4/reasoningEngines/77", "principal": PRINCIPAL},
        "components": {
            "kb-agent": {"registry": "projects/42/locations/us-east4/agents/agentregistry-kb",
                         "url": "https://kb.run.app"},
            "hr-records-agent": {"registry": "projects/42/locations/us-east4/agents/agentregistry-hr"},
            "tickets-mcp": {"registry": "projects/42/locations/us-east4/mcpServers/agentregistry-tickets",
                            "url": "https://tickets.run.app"},
            "directory-mcp": {"registry": "projects/42/locations/us-east4/mcpServers/agentregistry-dir"},
        }}},
}


@pytest.fixture()
def cfg():
    return DemoConfig.model_validate({"environment": {"project_id": "demo-proj", "region": "us-east4",
                                                      "resource_prefix": "agdemo"}})


@pytest.fixture()
def theme():
    return load_theme("helpdesk")


def render(cfg, theme, applied, ma=False, shared=False, state=STATE):
    return T.render(cfg, state, theme, set(applied), ma, shared, now=NOW)


def hcl_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def balanced(text: str) -> bool:
    code = re.sub(r'"(?:[^"\\]|\\.)*"', '""', re.sub(r"<<-(\w+)\n.*?\n\s*\1\n", "\n", text, flags=re.S))
    code = "\n".join(ln for ln in code.split("\n") if not ln.lstrip().startswith("#"))
    return all(code.count(a) == code.count(b) for a, b in ("{}", "[]", "()"))


def test_files_and_header(cfg, theme):
    files = render(cfg, theme, {"gw-egress", "allow-kb", "tickets-readonly-hints"})
    assert set(files) == {"main.tf", "variables.tf", "README.md"}
    main = files["main.tf"]
    assert "Generated by agdemo" in main and "2026-10-08T12:00:00Z" in main
    assert "Theme: helpdesk" in main
    assert "Policy state: gw-egress, allow-kb, tickets-readonly-hints · Model Armor off" in main
    assert "referenced, not managed" in main
    assert 'source  = "hashicorp/google"' in main and 'version = ">= 8.1.0"' in main
    for v in ("project_id", "project_number", "region", "prefix", "gateway_project_id"):
        assert f'variable "{v}"' in files["variables.tf"]
    assert 'default     = "demo-proj"' in files["variables.tf"]
    assert 'default     = "42"' in files["variables.tf"]           # project number from state
    assert all(balanced(f) for n, f in files.items() if n.endswith(".tf"))


def test_only_applied_policies(cfg, theme):
    main = render(cfg, theme, {"allow-kb"})["main.tf"]
    assert 'resource "google_iap_agent_registry_agent_iam_member" "allow_kb"' in main
    assert '# allow-kb: Helpdesk Agent can talk to KB Agent over A2A.' in main
    assert 'local.registry_ids["kb-agent"]' in main
    assert '"kb-agent"         = "agentregistry-kb"' in main
    assert f'orchestrator_principal = "{PRINCIPAL}"' in main
    assert 'role     = "roles/iap.egressor"' in main
    for absent in ("allow_hr", "tickets_all", "terraform_data", "model_armor_egress", "condition {",
                   "google_network_services_agent_gateway"):
        assert absent not in main


def test_mcp_server_allow_unconditional(cfg, theme):
    main = render(cfg, theme, {"tickets-all", "allow-directory"})["main.tf"]
    assert 'resource "google_iap_agent_registry_mcp_server_iam_member" "tickets_all"' in main
    assert 'resource "google_iap_agent_registry_mcp_server_iam_member" "allow_directory"' in main
    assert 'mcp_server_id = local.registry_ids["tickets-mcp"]' in main
    assert "condition {" not in main


def test_readonly_by_name_condition_matches_demo(cfg, theme):
    main = render(cfg, theme, {"tickets-readonly"})["main.tf"]
    cond = condition(theme, theme.policy("tickets-readonly"))
    assert "list_tickets" in cond["expression"] and "close_ticket" not in cond["expression"]
    assert f"expression  = {hcl_str(cond['expression'])}" in main
    assert f"title       = {hcl_str(cond['title'])}" in main
    assert 'resource "google_iap_agent_registry_mcp_server_iam_member" "tickets_readonly"' in main


def test_readonly_hints_condition_matches_demo(cfg, theme):
    main = render(cfg, theme, {"tickets-readonly-hints"})["main.tf"]
    cond = condition(theme, theme.policy("tickets-readonly-hints"))
    assert "mcp.tool.isReadOnly" in cond["expression"]
    assert f"expression  = {hcl_str(cond['expression'])}" in main


def test_both_gateways_one_patch(cfg, theme):
    main = render(cfg, theme, {"gw-egress", "gw-ingress"})["main.tf"]
    assert main.count('resource "terraform_data" "gateway_binding"') == 1
    assert "agentToAnywhereConfig = {" in main and "clientToAgentConfig = {" in main
    assert "agentGateway = local.egress_gateway" in main and "agentGateway = local.ingress_gateway" in main
    assert "updateMask=spec.deploymentSpec.agentGatewayConfig" in main
    assert "gcloud auth print-access-token" in main and "curl -sS --fail-with-body -X PATCH" in main
    assert "when    = destroy" in main and '{"agentGatewayConfig":{}}' in main
    assert "google_vertex_ai_reasoning_engine" in main and "agent_to_anywhere_config" in main
    assert 'agentGateways/${var.prefix}-egress"' in main


def test_ingress_only(cfg, theme):
    main = render(cfg, theme, {"gw-ingress"})["main.tf"]
    assert "clientToAgentConfig" in main and "agentToAnywhereConfig" not in main


def test_model_armor(cfg, theme):
    main = render(cfg, theme, set(), ma=True)["main.tf"]
    for path in ("egress", "ingress"):
        assert f'resource "google_network_security_authz_policy" "model_armor_{path}"' in main
        assert f'name           = "${{var.prefix}}-{path}-ma-policy"' in main
        assert f"resources = [local.model_armor_extension.{path}]" in main
        assert f"resources = [local.{path}_gateway]" in main
    assert main.count('policy_profile = "CONTENT_AUTHZ"') == 2
    assert 'action         = "CUSTOM"' in main
    assert "authzExtensions/${var.prefix}-ma-authz" in main
    assert "Model Armor on" in main


def test_include_shared(cfg, theme):
    files = render(cfg, theme, {"gw-egress", "allow-kb", "tickets-readonly"}, ma=True, shared=True)
    main = files["main.tf"]
    for r in ('"google_network_services_agent_gateway" "egress"', '"google_network_services_agent_gateway" "ingress"',
              '"google_network_services_authz_extension" "egress_iap"',
              '"google_network_services_authz_extension" "model_armor"',
              '"google_network_security_authz_policy" "egress_iap"', '"google_model_armor_template" "shield"',
              '"google_agent_registry_service" "kb_agent"', '"google_agent_registry_service" "tickets_mcp"',
              '"google_agent_registry_service" "platform"', '"google_iap_agent_registry_endpoint_iam_member" "platform"',
              '"google_service_account" "ui"', '"google_project_iam_member" "orchestrator"'):
        assert f"resource {r}" in main, r
    assert 'policy_profile = "REQUEST_AUTHZ"' in main
    assert 'type    = "A2A_AGENT_CARD"' in main and 'type    = "TOOL_SPEC"' in main
    assert '"readOnlyHint": true' in main and '"destructiveHint": true' in main
    assert '"url": "https://kb.run.app"' in main and 'url              = "https://tickets.run.app/mcp"' in main
    assert '"kb-agent"         = basename(google_agent_registry_service.kb_agent.registry_resource)' in main
    assert "egress_gateway  = google_network_services_agent_gateway.egress.id" in main
    assert "google_network_services_authz_extension.model_armor[local.gateway_project].id" in main
    assert "principalSet://agents.global.org-1.system.id.goog/attribute.platformContainer/aiplatform/projects/42" in main
    assert "service-99@gcp-sa-dep" in main
    assert "terraform import" in files["README.md"]
    assert balanced(main)


def test_policies_only_references_shared(cfg, theme):
    main = render(cfg, theme, {"allow-kb"})["main.tf"]
    assert "created by `./agdemo bootstrap`" in main
    assert "google_agent_registry_service" not in main


def test_placeholders_when_not_deployed(theme):
    files = T.render(None, None, theme, {"gw-egress", "allow-kb"}, False, False, now=NOW)
    main = files["main.tf"]
    assert "PLACEHOLDERS" in main and "REGISTRY_ID_KB_AGENT" in main and "ENGINE_ID" in main
    assert "Placeholders" in files["README.md"]


def test_readme_table(cfg, theme):
    readme = render(cfg, theme, {"gw-egress", "tickets-readonly-hints"}, ma=True)["README.md"]
    assert "| `tickets-readonly-hints` |" in readme and "with condition" in readme
    assert "terraform_data.gateway_binding" in readme
    assert "model_armor_{egress,ingress}" in readme


def test_state_line(theme):
    assert T.state_line(theme, [], False) == "no policies (wide open) · Model Armor off"
    assert T.state_line(theme, ["allow-kb", "gw-egress"], True) == "gw-egress, allow-kb · Model Armor on"


# ---------------------------------------------------------------- API (Demo mode)
def test_api_terraform_demo(client):  # noqa: F811
    client.post("/api/themes/helpdesk/reset", json={"mode": "demo"})
    client.post("/api/model-armor", json={"enabled": False, "mode": "demo"})
    client.post("/api/themes/helpdesk/policies/gw-egress", json={"action": "apply", "mode": "demo"})
    client.post("/api/themes/helpdesk/policies/allow-kb", json={"action": "apply", "mode": "demo"})
    r = client.get("/api/themes/helpdesk/terraform?mode=demo")
    assert r.status_code == 200
    body = r.json()
    assert body["source"] == "simulated"
    assert body["applied"] == ["gw-egress", "allow-kb"]
    assert body["model_armor"] is False and body["include_shared"] is False
    assert set(body["files"]) == {"main.tf", "variables.tf", "README.md"}
    assert '"allow_kb"' in body["files"]["main.tf"] and "terraform_data" in body["files"]["main.tf"]
    r = client.get("/api/themes/helpdesk/terraform?mode=demo&include_shared=true")
    assert "google_network_services_agent_gateway" in r.json()["files"]["main.tf"]
    client.post("/api/themes/helpdesk/reset", json={"mode": "demo"})


def test_api_terraform_unknown_theme(client):  # noqa: F811
    assert client.get("/api/themes/nope/terraform?mode=demo").status_code == 404
