"""Deployment state (config/state.json): IDs and URLs generated by the CLI, read by the UI backend.

Shape:
{
  "shared": {
    "egress_gateway": "projects/.../agentGateways/agdemo-egress",
    "ingress_gateway": "projects/.../agentGateways/agdemo-ingress",
    "ingress_gateway_url": "https://...",          # how clients call agents through the ingress gateway
    "model_armor_template": "projects/.../templates/agdemo-shield",
    "platform_registry_ids": {"<host>": "<registry resource name>"},
    "denied_caller_sa": "agdemo-denied-caller@...",
    "ui_url": "https://..."
  },
  "themes": {
    "<theme_id>": {
      "orchestrator": {"engine": "projects/.../reasoningEngines/123", "principal": "principal://..."},
      "components": {
        "<component_id>": {"url": "https://...run.app", "registry": "<registry resource name>",
                           "registry_extra": {"read": "...", "write": "..."}}
      }
    }
  }
}
"""
from __future__ import annotations

import json
import threading
from pathlib import Path
from typing import Any

from .config import CONFIG_DIR

STATE_PATH = CONFIG_DIR / "state.json"
_lock = threading.Lock()


def load_state(path: Path = STATE_PATH) -> dict[str, Any]:
    if not path.exists():
        return {"shared": {}, "themes": {}}
    return json.loads(path.read_text())


def save_state(state: dict[str, Any], path: Path = STATE_PATH) -> None:
    with _lock:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".tmp")
        tmp.write_text(json.dumps(state, indent=2, sort_keys=True))
        tmp.replace(path)


def update_state(*keys: str, value: Any, path: Path = STATE_PATH) -> dict[str, Any]:
    """update_state("themes", "helpdesk", "orchestrator", value={...})"""
    with _lock:
        state = load_state(path)
        node = state
        for k in keys[:-1]:
            node = node.setdefault(k, {})
        node[keys[-1]] = value
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(state, indent=2, sort_keys=True))
        return state


def theme_state(theme_id: str, path: Path = STATE_PATH) -> dict[str, Any]:
    return load_state(path).get("themes", {}).get(theme_id, {})
