// Client-side stand-in for agdemo_core/terraform.render (mock backend only). Same layout as the real export,
// with the shared-infrastructure section shortened. The real files come from GET /api/themes/{id}/terraform.
import type { Policy, TerraformExport, Theme } from "./types";

export interface MockTfCtx {
  project: string;
  projectNumber: string;
  region: string;
  prefix: string;
  principal: string;
  projectSet: string;
  engine: string;
  /** Additional orchestrators (CONTRACTS §12): their own engine and Agent Identity principal. */
  sources?: Record<string, { name: string; principal: string; engine: string }>;
  registryId: (cid: string) => string;
  condition: (theme: Theme, p: Policy) => { title: string; expression: string } | null;
}

const q = (s: string) => JSON.stringify(s).replace(/\$\{/g, "$${");
const ident = (s: string) => s.replace(/[^A-Za-z0-9_]/g, "_");
const pad = (rows: [string, string][], ind: string) => {
  const w = Math.max(...rows.map(([k]) => k.length));
  return rows.map(([k, v]) => `${ind}${k.padEnd(w)} = ${v}`).join("\n");
};

export function stateLine(theme: Theme, applied: Set<string>, ma: boolean): string {
  const ids = theme.policies.filter((p) => applied.has(p.id)).map((p) => p.id);
  return `${ids.length ? ids.join(", ") : "no policies (wide open)"} · Model Armor ${ma ? "on" : "off"}`;
}

export function mockTerraform(theme: Theme, applied: Set<string>, ma: boolean, shared: boolean, live: boolean, c: MockTfCtx): TerraformExport {
  const pols = theme.policies.filter((p) => applied.has(p.id));
  const src = (p: Policy) => (p.params.source ? String(p.params.source) : null);
  // Primary engine's bindings; additional orchestrators get their own binding resource below (CONTRACTS §12).
  const gws = new Map(pols.filter((p) => p.type === "gateway_attach" && !src(p)).map((p) => [String(p.params.path ?? "egress"), p]));
  const srcGws = pols.filter((p) => p.type === "gateway_attach" && src(p) && c.sources?.[src(p)!]);
  const usedSources = [...new Set(pols.map(src).filter((x): x is string => !!x && !!c.sources?.[x]))];
  const egress = pols.filter((p) => p.type !== "gateway_attach");
  const ts = new Date().toISOString().replace(/\.\d+Z$/, "Z");
  const line = stateLine(theme, applied, ma);
  const out: string[] = [];
  out.push(
    [
      `# Generated by agdemo (Agent Gateway & Agent Registry demo) at ${ts}`,
      `# Theme: ${theme.id} (${theme.name})`,
      `# Policy state: ${line}`,
      `# Scope: ${shared ? "policies + shared infrastructure" : "policies only"}`,
      "#",
      shared
        ? "# Shared resources are managed below as well. If they already exist (created by `./agdemo bootstrap` /\n# `deploy-theme`), import them first (see README.md)."
        : "# Shared resources (Agent Gateways, authz extensions, Model Armor template, Agent Registry entries) are\n# created by `./agdemo bootstrap` and `./agdemo deploy-theme`; they are referenced by name in `locals`.",
      "# The Agent Runtime engine and the Cloud Run services are created by `./agdemo deploy-theme` and are",
      "# referenced, not managed.",
      "# Nothing here has been applied by agdemo: run `terraform plan` and review it before applying.",
      "# (Mock backend: sample output.)",
      "",
      'terraform {\n  required_version = ">= 1.5"\n\n  required_providers {\n    google = {\n      source  = "hashicorp/google"\n      version = ">= 8.1.0"\n    }\n  }\n}',
      "",
      'provider "google" {\n  project = var.project_id\n  region  = var.region\n}',
      "",
    ].join("\n"),
  );
  const loc: string[] = [
    pad(
      [
        ["gateway_project", "coalesce(var.gateway_project_id, var.project_id)"],
        ["gateway_project_number", "coalesce(var.gateway_project_number, var.project_number)"],
      ],
      "  ",
    ),
    "",
    "  # Created by `./agdemo deploy-theme` (referenced, not managed by this configuration).",
    pad(
      [
        ["engine", q(c.engine)],
        ["orchestrator_principal", q(c.principal)],
      ],
      "  ",
    ),
    "",
  ];
  if (usedSources.length) {
    loc.push("  # Additional Agent Runtime agents (own engine and Agent Identity), created by `./agdemo deploy-theme`.");
    loc.push(
      pad(
        usedSources.flatMap((id): [string, string][] => [
          [`${ident(id)}_engine`, q(c.sources![id].engine)],
          [`${ident(id)}_principal`, q(c.sources![id].principal)],
        ]),
        "  ",
      ),
      "",
    );
  }
  if (shared) {
    loc.push("  # Agent Gateways (managed below).", pad([["egress_gateway", "google_network_services_agent_gateway.egress.id"], ["ingress_gateway", "google_network_services_agent_gateway.ingress.id"]], "  "));
  } else {
    loc.push(
      "  # Shared resources created by `./agdemo bootstrap` (referenced by name).",
      pad(
        [
          ["egress_gateway", '"projects/${local.gateway_project}/locations/${var.region}/agentGateways/${var.prefix}-egress"'],
          ["ingress_gateway", '"projects/${var.project_id}/locations/${var.region}/agentGateways/${var.prefix}-ingress"'],
        ],
        "  ",
      ),
    );
    if (ma)
      loc.push(
        "  model_armor_extension = {",
        '    egress  = "projects/${local.gateway_project}/locations/${var.region}/authzExtensions/${var.prefix}-ma-authz"',
        '    ingress = "projects/${var.project_id}/locations/${var.region}/authzExtensions/${var.prefix}-ma-authz"',
        "  }",
      );
  }
  loc.push("", "  # Agent Registry projection ids (agents/<id>, mcpServers/<id>).", "  registry_ids = {");
  loc.push(pad(theme.components.map((co) => [q(co.id), shared ? `basename(google_agent_registry_service.${ident(co.id)}.registry_resource)` : q(c.registryId(co.id))]), "    "), "  }");
  if (gws.size) {
    loc.push("", "  # agentGatewayConfig for the engine: every direction that is currently attached.", "  gateway_binding_body = jsonencode({", "    spec = {", "      deploymentSpec = {", "        agentGatewayConfig = {");
    for (const [path, key] of [["egress", "agentToAnywhereConfig"], ["ingress", "clientToAgentConfig"]])
      if (gws.has(path)) loc.push(`          ${key} = {`, `            agentGateway = local.${path}_gateway`, "          }");
    loc.push("        }", "      }", "    }", "  })");
  }
  out.push(`locals {\n${loc.join("\n")}\n}\n`);

  if (gws.size) {
    const dirs = [...gws.entries()];
    out.push(
      "# ---- Gateway binding (gateway_attach) ----\n",
      dirs.map(([, p]) => `# ${p.id}: ${p.text}`).join("\n"),
      "#\n# No Terraform resource binds an existing Agent Runtime engine to an Agent Gateway, so this runs the same\n# PATCH the demo makes (an LRO that redeploys the engine). Destroying it detaches every direction.\n#\n# Teams that manage the engine in Terraform set google_vertex_ai_reasoning_engine.spec.deployment_spec\n# .agent_gateway_config instead (google >= 8.1.0; needs an import of the existing engine):\n#\n#   spec {\n#     deployment_spec {\n#       agent_gateway_config {",
      dirs.map(([path]) => `#         ${path === "egress" ? "agent_to_anywhere_config" : "client_to_agent_config"} {\n#           agent_gateway = local.${path}_gateway\n#         }`).join("\n"),
      "#       }\n#     }\n#   }",
      'resource "terraform_data" "gateway_binding" {\n  input = {\n    url = "https://${var.region}-aiplatform.googleapis.com/v1/${local.engine}?updateMask=spec.deploymentSpec.agentGatewayConfig"\n  }\n  triggers_replace = [local.engine, local.gateway_binding_body]\n\n  provisioner "local-exec" {\n    command = <<-EOT\n      curl -sS --fail-with-body -X PATCH "$URL" \\\n        -H "Authorization: Bearer $(gcloud auth print-access-token)" \\\n        -H "Content-Type: application/json" \\\n        -d "$BODY"\n    EOT\n    environment = {\n      URL  = self.input.url\n      BODY = local.gateway_binding_body\n    }\n  }\n\n  provisioner "local-exec" {\n    when    = destroy\n    command = <<-EOT\n      curl -sS --fail-with-body -X PATCH "$URL" \\\n        -H "Authorization: Bearer $(gcloud auth print-access-token)" \\\n        -H "Content-Type: application/json" \\\n        -d \'{"spec":{"deploymentSpec":{"agentGatewayConfig":{}}}}\'\n    EOT\n    environment = {\n      URL = self.input.url\n    }\n  }\n}\n',
    );
  }
  for (const p of srcGws) {
    const id = src(p)!;
    const n = ident(id);
    out.push(
      `# ${p.id}: ${p.text}\n# ${c.sources![id].name} has its own engine: bind it to the same shared egress gateway.\n` +
        `resource "terraform_data" "gateway_binding_${n}" {\n  input = {\n    url  = "https://\${var.region}-aiplatform.googleapis.com/v1/\${local.${n}_engine}?updateMask=spec.deploymentSpec.agentGatewayConfig"\n` +
        `    body = jsonencode({ spec = { deploymentSpec = { agentGatewayConfig = { agentToAnywhereConfig = { agentGateway = local.egress_gateway } } } } })\n  }\n` +
        `  triggers_replace = [local.${n}_engine]\n\n  provisioner "local-exec" {\n    command = "curl -sS --fail-with-body -X PATCH \\"$URL\\" -H \\"Authorization: Bearer $(gcloud auth print-access-token)\\" -H \\"Content-Type: application/json\\" -d \\"$BODY\\""\n` +
        `    environment = {\n      URL  = self.input.url\n      BODY = self.input.body\n    }\n  }\n}\n`,
    );
  }
  if (egress.length) {
    out.push("# ---- Egress allow policies: roles/iap.egressor on Agent Registry entries ----\n");
    for (const p of egress) {
      const target = String(p.params.target);
      const agent = theme.components.find((co) => co.id === target)?.kind === "a2a_agent";
      const [rtype, key] = agent ? ["google_iap_agent_registry_agent_iam_member", "agent_id"] : ["google_iap_agent_registry_mcp_server_iam_member", "mcp_server_id"];
      const cond = c.condition(theme, p);
      out.push(
        `# ${p.id}: ${p.text}\nresource "${rtype}" "${ident(p.id)}" {\n` +
          pad(
            [
              ["project", "local.gateway_project_number"],
              ["location", "var.region"],
              [key, `local.registry_ids[${q(target)}]`],
              ["role", q("roles/iap.egressor")],
              ["member", src(p) && c.sources?.[src(p)!] ? `local.${ident(src(p)!)}_principal` : "local.orchestrator_principal"],
            ],
            "  ",
          ) +
          (cond ? `\n\n  condition {\n${pad([["title", q(cond.title)], ["expression", q(cond.expression)]], "    ")}\n  }` : "") +
          "\n}\n",
      );
    }
  }
  if (ma) {
    out.push("# ---- Model Armor (CONTENT_AUTHZ authz policy on each gateway) ----\n");
    for (const path of ["egress", "ingress"])
      out.push(
        `resource "google_network_security_authz_policy" "model_armor_${path}" {\n` +
          pad(
            [
              ["project", path === "egress" ? "local.gateway_project" : "var.project_id"],
              ["location", "var.region"],
              ["name", `"\${var.prefix}-${path}-ma-policy"`],
              ["policy_profile", '"CONTENT_AUTHZ"'],
              ["action", '"CUSTOM"'],
            ],
            "  ",
          ) +
          `\n\n  target {\n    resources = [local.${path}_gateway]\n  }\n\n  custom_provider {\n    authz_extension {\n      resources = [${shared ? `google_network_services_authz_extension.model_armor.id` : `local.model_armor_extension.${path}`}]\n    }\n  }\n}\n`,
      );
  }
  if (shared) {
    out.push(
      "# ---- Shared infrastructure (created by ./agdemo bootstrap) ----\n",
      ...["egress", "ingress"].map(
        (path) =>
          `resource "google_network_services_agent_gateway" "${path}" {\n${pad(
            [
              ["project", path === "egress" ? "local.gateway_project" : "var.project_id"],
              ["location", "var.region"],
              ["name", `"\${var.prefix}-${path}"`],
            ],
            "  ",
          )}\n\n  google_managed {\n    governed_access_path = "${path === "egress" ? "AGENT_TO_ANYWHERE" : "CLIENT_TO_AGENT"}"\n  }\n}\n`,
      ),
      `resource "google_network_services_authz_extension" "egress_iap" {\n${pad(
        [
          ["project", "local.gateway_project"],
          ["location", "var.region"],
          ["name", '"${var.prefix}-egress-iap-authz"'],
          ["service", '"iap.googleapis.com"'],
          ["timeout", '"1s"'],
        ],
        "  ",
      )}\n  metadata = {\n    iapPolicyVersion = "V1"\n  }\n}\n`,
      `resource "google_model_armor_template" "shield" {\n${pad(
        [
          ["project", "var.project_id"],
          ["location", "var.region"],
          ["template_id", '"${var.prefix}-shield"'],
        ],
        "  ",
      )}\n\n  filter_config {\n    pi_and_jailbreak_filter_settings {\n      filter_enforcement = "ENABLED"\n      confidence_level   = "MEDIUM_AND_ABOVE"\n    }\n  }\n}\n`,
      ...theme.components.map(
        (co) =>
          `resource "google_agent_registry_service" "${ident(co.id)}" {\n${pad(
            [
              ["project", "local.gateway_project"],
              ["location", "var.region"],
              ["service_id", `"\${var.prefix}-${theme.id}-${co.id}"`],
            ],
            "  ",
          )}\n\n  ${co.kind === "a2a_agent" ? 'agent_spec {\n    type    = "A2A_AGENT_CARD"' : 'mcp_server_spec {\n    type    = "TOOL_SPEC"'}\n    content = jsonencode({ /* … */ })\n  }\n}\n`,
      ),
      "# … platform endpoints (google_agent_registry_service.platform + _endpoint_iam_member), service accounts and\n# project IAM are in the real export.\n",
    );
  }
  const main = out.join("\n").replace(/\n{3,}/g, "\n\n");
  const variables = [
    ["project_id", "Project for Agent Runtime, the ingress gateway, Cloud Run and Model Armor.", q(c.project)],
    ["project_number", "Number of project_id (service agents and principals use it).", q(c.projectNumber)],
    ["gateway_project_id", "Project for the egress gateway and Agent Registry (null = project_id).", "null"],
    ["gateway_project_number", "Number of the gateway project (null = project_number).", "null"],
    ["region", "Region for gateways, Agent Runtime, Agent Registry and Cloud Run.", q(c.region)],
    ["prefix", "Resource name prefix (resource_prefix in config/demo.yaml).", q(c.prefix)],
  ]
    .map(([n, d, v]) => `variable "${n}" {\n${pad([["description", q(d)], ["type", "string"], ["default", v]], "  ")}\n}\n`)
    .join("\n");
  const readme = `# Terraform export: ${theme.name} (\`${theme.id}\`)\n\nGenerated by agdemo at ${ts} (mock backend). Policy state: **${line}**.\n\n**Managed:** ${
    shared ? "policies and the shared infrastructure." : "policies only; shared resources are referenced by name."
  }\n\n**Referenced, not managed:** the Agent Runtime engine and the Cloud Run services (created by \`./agdemo deploy-theme\`).\n\n| Policy | What it does |\n|---|---|\n${pols.map((p) => `| \`${p.id}\` | ${p.text} |`).join("\n")}${ma ? "\n| Model Armor | Screened on both gateways |" : ""}\n\n\`\`\`sh\nterraform init\nterraform plan\n\`\`\`\n`;
  return {
    theme: theme.id,
    files: { "main.tf": main.trimEnd() + "\n", "variables.tf": `# Generated by agdemo.\n\n${variables}`, "README.md": readme },
    applied: pols.map((p) => p.id),
    model_armor: ma,
    include_shared: shared,
    source: live ? "live" : "simulated",
    state_line: line,
  };
}
